name: 'taxi_rides_ny'
version: '1.0.0'
config-version: 2

vars:
  surrogate_key_treat_nulls_as_empty_strings: true #turn on legacy behavior
  payment_type_values: [1,2,3,4,5,6]

profile: 'default'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  taxi_rides_ny:
    taxi_zone_lookup:
      +column_types:
        locationid: numeric